# Generated by Django 4.2.30 on 2026-05-01 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category_type', models.CharField(choices=[('time', 'Time-Based'), ('occasion', 'Occasion'), ('meal', 'Meal Type'), ('diet', 'Dietary'), ('course', 'Course'), ('festival', 'Festival / Seasonal')], default='occasion', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class e.g. fa-bolt', max_length=60)),
                ('emoji', models.CharField(blank=True, max_length=8)),
                ('color', models.CharField(default='#FF6B35', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('max_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegionalLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('native_name', models.CharField(blank=True, max_length=100)),
                ('script', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regional Language',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('native_name', models.CharField(blank=True, max_length=120)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, choices=[('north', 'North India'), ('south', 'South India'), ('east', 'East India'), ('west', 'West India'), ('central', 'Central India'), ('northeast', 'Northeast India'), ('union', 'Union Territory')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cuisine_summary', models.TextField(blank=True, help_text="Brief summary of the state's cuisine for the state page")),
                ('banner_image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('additional_languages', models.ManyToManyField(blank=True, help_text='Other languages spoken in this state', related_name='additional_states', to='recipes.regionallanguage')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='recipes.country')),
                ('primary_language', models.ForeignKey(blank=True, help_text='Main language of this state — used for language switcher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_states', to='recipes.regionallanguage')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('description', models.TextField()),
                ('diet_type', models.CharField(choices=[('veg', 'Vegetarian 🥦'), ('nonveg', 'Non-Vegetarian 🍗'), ('vegan', 'Vegan 🌱'), ('jain', 'Jain 🌿'), ('eggt', 'Eggetarian 🥚')], default='veg', max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('prep_time', models.PositiveIntegerField(default=0, help_text='minutes')),
                ('cook_time', models.PositiveIntegerField(default=0, help_text='minutes')),
                ('servings', models.PositiveIntegerField(default=4)),
                ('calories_per_serving', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL (Unsplash etc.) — used when no file uploaded')),
                ('is_trending', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('festival_tag', models.CharField(blank=True, help_text='e.g. Diwali Special, Eid Special, Pongal', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='recipes', to='recipes.category')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.country')),
                ('cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.cuisine')),
                ('state', models.ForeignKey(blank=True, help_text='Indian state this recipe originates from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.state')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=60)),
                ('unit', models.CharField(blank=True, max_length=60)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='cuisine',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='cuisines', to='recipes.state'),
        ),
        migrations.AddField(
            model_name='country',
            name='default_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_countries', to='recipes.regionallanguage'),
        ),
        migrations.CreateModel(
            name='UserSavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'recipe')},
            },
        ),
        migrations.CreateModel(
            name='RecipeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.regionallanguage')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='recipes.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'language')},
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('instruction', models.TextField()),
                ('tip', models.CharField(blank=True, max_length=400)),
                ('time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('recipe', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
